// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piqvvcdhmhmiamzlucgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpcXZ2Y2RobWhtaWFtemx1Y2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MDY1ODAsImV4cCI6MjA3MTQ4MjU4MH0.tK4ZMM4tOIzqGi4bjp8VnlOteUVhyxZ78CABXITJnAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});